### ISSUE TITLE
monkey setup issue

### ISSUE THREAD

**Issue by mm0ck3r** [eclipse/iottestware.fuzzing#8]
![image](https://user-images.githubusercontent.com/16663734/118568788-8565c380-b7b3-11eb-90ba-52d42b5b6d83.png)

why "Python3" ?????

Thank you.

**Comment by alexanderkaiser** [comment]
Thank you for issuing this point.

The intention of checking for Python3 is because the Fuzzer was written entirely in Python3. 
However, I assume you are pointing at [P]ython, right?

Could you provide a fix for the issue?

**Comment by mm0ck3r** [comment]
In Ubuntu Linux, Python3 and python3 is different. Sorry to tell you that it's important. 😂😂

**Comment by alexanderkaiser** [comment]
You could also try to alias Python3 to your python3 😉
I'd assume experienced Pythoners might just simply skip that script and use `proxy.py` directly.

**Comment by mm0ck3r** [comment]
Yes! In fact, I have already installed monkey. Thank You :)
